import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from "framer-motion";
const EventModal = ({ event, onClose, onJoin }) => {
    if (!event)
        return null;
    // 🧭 Safe location formatting
    const locationText = typeof event.location === "object"
        ? `${event.city || "Unknown City"} (${event.location.coordinates?.[1]?.toFixed(2)}, ${event.location.coordinates?.[0]?.toFixed(2)})`
        : event.location || event.city || "Unknown";
    return (_jsx(AnimatePresence, { children: event && (_jsx(motion.div, { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-3", initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, children: _jsxs(motion.div, { className: "relative bg-white/95 dark:bg-gray-900/90 rounded-2xl p-5 sm:p-7 md:p-8 max-w-md sm:max-w-lg w-full shadow-2xl border border-gray-200 dark:border-gray-700 overflow-y-auto max-h-[90vh]", initial: { scale: 0.8, opacity: 0, y: 40 }, animate: { scale: 1, opacity: 1, y: 0 }, exit: { scale: 0.85, opacity: 0, y: 20 }, transition: { duration: 0.3, type: "spring" }, onClick: (e) => e.stopPropagation(), children: [_jsx("button", { onClick: onClose, className: "absolute right-4 top-4 text-gray-500 hover:text-gray-800 dark:hover:text-gray-200 text-xl sm:text-2xl", children: "\u2716" }), event.banner && (_jsx("img", { src: event.banner, alt: event.title, className: "rounded-xl mb-4 w-full h-40 sm:h-48 md:h-52 object-cover shadow-md" })), _jsx("h2", { className: "text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-2 text-center sm:text-left", children: event.title }), _jsxs("p", { className: "text-sm sm:text-base text-gray-600 dark:text-gray-400 mb-3 text-center sm:text-left", children: ["\uD83D\uDCCD ", locationText, " \u2022 ", new Date(event.date).toLocaleString()] }), _jsx("p", { className: "text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed mb-4 text-justify", children: event.description }), _jsxs("div", { className: "mt-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-0", children: [_jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400 text-center sm:text-left", children: ["\uD83D\uDC65 ", event.currentParticipants, "/", event.maxParticipants, " joined"] }), onJoin && (_jsx("button", { onClick: () => onJoin(event._id ?? event.id ?? ""), className: "w-full sm:w-auto bg-gradient-to-r from-indigo-500 to-pink-500 text-white px-6 py-2 rounded-lg font-medium hover:shadow-lg transition-transform hover:scale-105 text-center", children: "Join Now" }))] })] }) })) }));
};
export default EventModal;
