import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { FaGithub, FaLinkedin, FaInstagram } from "react-icons/fa";
const Footer = () => {
    const year = new Date().getFullYear();
    return (_jsx("footer", { className: "relative bg-gradient-to-br from-indigo-50 to-pink-50 dark:from-gray-900 dark:to-gray-950 border-t border-gray-200/50 dark:border-gray-800/70 mt-10", children: _jsxs("div", { className: "max-w-6xl mx-auto px-5 py-10 text-center md:text-left", children: [_jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 items-center", children: [_jsxs("div", { className: "flex flex-col items-center sm:items-start text-center sm:text-left", children: [_jsxs("div", { className: "flex items-center gap-3 mb-3", children: [_jsx("div", { className: "w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-pink-500 flex items-center justify-center text-white font-bold shadow-md", children: "EF" }), _jsx("h1", { className: "text-xl font-semibold text-gray-800 dark:text-gray-100", children: "EventFinder" })] }), _jsxs("p", { className: "text-sm text-gray-600 dark:text-gray-400 max-w-xs leading-relaxed", children: ["Discover, join, and create amazing events around you \u2014 built with", _jsx("span", { className: "text-pink-500 font-semibold", children: " \u2764 " }), "by ", _jsx("span", { className: "font-semibold text-indigo-600", children: "Gautam" }), "."] })] }), _jsx("div", { className: "flex flex-wrap justify-center sm:justify-center md:justify-center gap-4 sm:gap-6 text-sm font-medium", children: [
                                { name: "Home", to: "/" },
                                { name: "About", to: "/about" },
                                { name: "Create", to: "/create" },
                                { name: "Login", to: "/login" },
                            ].map((link) => (_jsx(Link, { to: link.to, className: "text-gray-700 dark:text-gray-300 hover:text-indigo-500 transition", children: link.name }, link.name))) }), _jsxs("div", { className: "flex justify-center md:justify-end gap-5", children: [_jsx("a", { href: "https://github.com/codergautam900", target: "_blank", rel: "noopener noreferrer", className: "text-gray-600 dark:text-gray-400 hover:text-indigo-500 transition text-2xl", children: _jsx(FaGithub, {}) }), _jsx("a", { href: "https://linkedin.com/in/codergautam900", target: "_blank", rel: "noopener noreferrer", className: "text-gray-600 dark:text-gray-400 hover:text-indigo-500 transition text-2xl", children: _jsx(FaLinkedin, {}) }), _jsx("a", { href: "https://instagram.com", target: "_blank", rel: "noopener noreferrer", className: "text-gray-600 dark:text-gray-400 hover:text-pink-500 transition text-2xl", children: _jsx(FaInstagram, {}) })] })] }), _jsxs("div", { className: "mt-8 text-center text-xs text-gray-500 dark:text-gray-500 border-t border-gray-200/40 dark:border-gray-800/40 pt-4", children: ["\u00A9 ", year, " ", _jsx("span", { className: "font-semibold text-indigo-600", children: "EventFinder" }), ". All rights reserved."] })] }) }));
};
export default Footer;
